Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FirstASPNETWebApp.Models
{
    public class ValidNum : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            int intValue = (int)value;

            if (intValue >= 0 && intValue <= 100)
            {
                return ValidationResult.Success;
            }
            else
            {
                return new ValidationResult("Value must be between 0 and 100.");
            }
        }
    }
    public class GradeCalcModel
    {
        //Creates getters and setters for From variable
        [Required]
        [Range(0, 100, ErrorMessage = "Value must be between 0 and 100.")]
        public int Assignments { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Value must be between 0 and 100.")]
        public int GroupProjects { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Value must be between 0 and 100.")]
        public int Quizzes { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Value must be between 0 and 100.")]
        public int Midterm { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Value must be between 0 and 100.")]
        public int Final { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Value must be between 0 and 100.")]
        public int INTEX { get; set; }
    }
}

Controllers/BlahController.cs
using FirstASPNETWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FirstASPNETWebApp.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View(); 
        }

        [HttpGet]
        public IActionResult GradeCalc()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalc (GradeCalcModel model)
        {
            if (ModelState.IsValid)
            {
                return GradeCalc();
            }
            else
            {
                return View(model);
            }
        }
    }
}

Views/Blah/GradeCalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model GradeCalcModel;

<h2>Grade Calculator: Enter your percent score as a whole number (ex. 92)</h2>
<form id="gCalc" method="post" class="form-control" asp-controller="Blah" asp-action="GradeCalc">
    <label class="form-label">Assignments</label>
    <input class="form-control" id="assignments" asp-for="Assignments" />
    @Html.ValidationMessageFor(m => m.Assignments)
    <br />
    <label class="form-label">Group Projects</label>
    <input class="form-control" id="groupProjects" asp-for="GroupProjects" />
    @Html.ValidationMessageFor(m => m.GroupProjects)
    <br />
    <label class="form-label">Quizzes</label>
    <input class="form-control" id="quizzes" asp-for="Quizzes" />
    @Html.ValidationMessageFor(m => m.Quizzes)
    <br />
    <label class="form-label">Midterm Exam</label>
    <input class="form-control" id="midterm" asp-for="Midterm" />
    @Html.ValidationMessageFor(m => m.Midterm)
    <br />
    <label class="form-label">Final Exam</label>
    <input class="form-control" id="final" asp-for="Final" />
    @Html.ValidationMessageFor(m => m.Final)
    <br />
    <label class="form-label">INTEX</label>
    <input class="form-control" id="intex" asp-for="INTEX" />
    @Html.ValidationMessageFor(m => m.INTEX)
    <br />
    <input id="btnSend" type="submit" value="Calculate Grade" class="btn btn-primary" />
    <br />
    <textarea id="letterGrade" value="" class="form-control"></textarea>

    <div asp-validation-summary="All"></div>

</form>

<script src="~/js/gradeCalc.js"></script>

Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Website About Trek Lewis";
}
<!--Trek Lewis: Mission 4, this is a website about myself with a grade calculator attached.-->
<!--Body elements including title, image, what I hope to learn from this course, job options, and a grade calculator-->
<h1 class="container-fluid">Trek Lewis Learns to Build a WebApp in ASP.NET</h1>

<!--Image of me doing my favorite activity with a description-->
<img src="~/img/IMG_7456.jpg" />
<p>Shreddin the slopes</p>
<br />

<!--What I hope to get out of this class by the end of the semester-->
<p>
    By the end of this class I hope to be able to build the framework for an enterprise-ready web application from memory.
</p>
<p>
    I also want to develop stronger troubleshooting skills that will be useful in industry.
</p>
<br/>

<!--Top job picks out of undergrad-->
<h2>Top 3 Jobs</h2>
<ul class="list-group">
    <li class="list-group-item-action">Private Equity Analyst</li>
    <li class="list-group-item-action">Investment Banking Analyst</li>
    <li class="list-group-item-action">Web Developer for a startup</li>
</ul>
<br />
<br />

<!--Grade calculator form-->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/main.css" rel="stylesheet" />
    <link href="~/css/bootstrap-5.3.0-alpha1-dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="~/img/download (1).png">
</head>

<body class="bg-dark-subtle">

    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalc">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="~/js/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/css/bootstrap-5.3.0-alpha1-dist/js/bootstrap.js"></script>

</body>
</html>